### ISSUE TITLE
Ошибки при включении проекта

### ISSUE THREAD

**Issue by nazar-lazarchuk** [droganaida/resumable-upload-demo#1]
1) 'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! resumable-upload-demo-blondiecode@1.0.0 dev: `NODE_ENV=development node app.js`

2) Error: ENOENT: no such file or directory, scandir 'E:\projects\resumable-upload-demo\files'
    at Object.readdirSync (fs.js:974:3)
    at Object.exports.clearFolder (E:\projects\resumable-upload-demo\libs\fileUpload.js:25:22)
    at exports.get (E:\projects\resumable-upload-demo\routes\main.js:8:20)
    at Layer.handle [as handle_request] (E:\projects\resumable-upload-demo\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\projects\resumable-upload-demo\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (E:\projects\resumable-upload-demo\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (E:\projects\resumable-upload-demo\node_modules\express\lib\router\layer.js:95:5)
    at E:\projects\resumable-upload-demo\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (E:\projects\resumable-upload-demo\node_modules\express\lib\router\index.js:335:12)
    at next (E:\projects\resumable-upload-demo\node_modules\express\lib\router\index.js:275:10) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'E:\\projects\\resumable-upload-demo\\files'
}

3) (node:30056) UnhandledPromiseRejectionWarning: Error: Cannot find module 'ejs'

4) SyntaxError: Unexpected token '.' in E:\projects\resumable-upload-demo\templates\error\error.ejs while compiling ejs

**Comment by Savr123** [comment]
2. Just create "files" folder in the direcotory next to app.js
    I think we should correct .gitignore file next to app.js file and add new .gitignore in "files" folder with  "*"
3. install "ejs" - npm i ejs
4. correct sytax in ./template/main/main.ejs and ./temlate/error/error.ejs (something like this  ```<%- include ('../common/scriptPack.ejs'); -%>```
I think this should help
